### ISSUE TITLE
Enable arbitrary form field attributes

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-forms#113]
For example, `autocomplete="tel"`.

The principal use use for this would be to allow users to enable [autofill](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill) in their forms.

**Comment by martin-langhoff** [comment]
Thanks! Yes this would be a great little feature to have. Without it, we do get autocomplete, but keyed in completely arbitrarily.

**Comment by czpython** [comment]
Closed by https://github.com/aldryn/aldryn-forms/pull/141
