### ISSUE TITLE
Error submitting form - but no error in log

### ISSUE THREAD

**Issue by pinksharpii** [aldryn/aldryn-forms#115]
I have a form on our client site that displays the "Error message" every time the form submits. But nothing gets logged in our error log. None of the individual fields have error messages - just the form overall.

I have all the necessary requirements in INSTALLED_APPS.

The email backend is set to 'django.core.mail.backends.console.EmailBackend'. 

Why is it erroring out? We are running The latest version of aldryn-forms (2.2.1) and Django 1.9.

**Comment by czpython** [comment]
Hello @pinksharpii,
Is the error message a server error or a client facing error?
Can you provide us with a screencast of the issue?

**Comment by pinksharpii** [comment]
I'm not sure. I have 3 screenshots. The first is just the error it's displaying - you can see in the second screenshot, it's coming from the Error message field in the form settings. Lastly, the recipients - you can see I am a recipient. I'm not sure if this helps. But I'm really not getting much of anything for an error. Everything is a 200 response in the Network tab in Chrome.. and nothing in my Django project error log.

![screen shot 2017-05-11 at 10 18 56 am](https://cloud.githubusercontent.com/assets/3431241/25957182/55478108-3633-11e7-836c-6eefcf5d9e0f.png)
![screen shot 2017-05-11 at 10 19 18 am](https://cloud.githubusercontent.com/assets/3431241/25957181/554756d8-3633-11e7-8f0d-0dd360285ea6.png)
![screen shot 2017-05-11 at 10 19 23 am](https://cloud.githubusercontent.com/assets/3431241/25957183/554801b4-3633-11e7-89b0-c008b5f18955.png)

**Comment by czpython** [comment]
Hello @pinksharpii,
Can you post the request form data being sent to the server?

Something like:

<img width="550" alt="sample-form-data" src="https://cloud.githubusercontent.com/assets/994951/26037272/e841255e-38bd-11e7-9acd-f0918f80a681.png">

**Comment by pinksharpii** [comment]
![screen shot 2017-05-15 at 12 41 17 pm](https://cloud.githubusercontent.com/assets/3431241/26070876/d12d1f72-396b-11e7-85df-8dfc4b9f8abd.png)

**Comment by czpython** [comment]
Strange.. is `en-us` in your `settings.LANGUAGES`?
There's a hidden language field, its possible that if `en-us` is not in your `settings.LANGUAGES`, the form fails validation.

**Comment by pinksharpii** [comment]
In settings.py, we have:
LANGUAGE_CODE = 'en-us'
Should it also be set in LANGUAGES variable?

**Comment by czpython** [comment]
Yes it should also be in `LANGUAGES`.

**Comment by pinksharpii** [comment]
Adding en-us to the LANGUAGES seemed to work. Thank you. 
I'm running into another issue now though - not sure if it's related. No form data from the fields is getting sent with the form. Based on the documentation I can't tell what, if anything, I did wrong.

![screen shot 2017-05-16 at 8 14 07 am](https://cloud.githubusercontent.com/assets/3431241/26107956/a8ae30e0-3a10-11e7-9732-f7823bfb8ddc.png)

**Comment by czpython** [comment]
Can you get the id of that form submission record and then in the shell run:

```python
from aldryn_forms.models import FormSubmission

submission = FormSubmission.objects.get(pk=your_submission_id)
print(submission.data)
```

**Comment by pinksharpii** [comment]
I'm not sure where I need to run that. Sorry, I'm new to this. If I have my server running and do that, nothing happens. I get an error when trying to do it in the Python Console in PyCharm.

I just went into the database instead. And data is just empty [] in the table.

**Comment by czpython** [comment]
No worries, good idea to check db directly :)

Can you post a screenshot of what the form structure looks like?
Something like this:

<img width="1098" alt="form-structure" src="https://cloud.githubusercontent.com/assets/994951/26131784/23e62110-3a6a-11e7-86bd-f0ad614ab913.png">

**Comment by pinksharpii** [comment]
I'm using Aldryn Bootstrap to structure the form fields - but they are all nested inside the Form element.

![screen shot 2017-05-16 at 6 08 56 pm](https://cloud.githubusercontent.com/assets/3431241/26131983/da40ab04-3a62-11e7-9410-fd35623a621b.png)

**Comment by pinksharpii** [comment]
I think we got it figured out. I think the last issue was due to us changing some things around with the sites.json file in the project.

But adding the language code to LANGUAGES definitely fixed the form overall, thanks.
