### ISSUE TITLE
Why require redirect? and alert message only displayed to logged in users.

### ISSUE THREAD

**Issue by pinksharpii** [aldryn/aldryn-forms#122]
I'm working on a client site and have noticed that the grey alert that displays the success message after a form has been submitted is only being displayed to logged out users. Is there a way we can change this behavior?
![grey-alert](https://user-images.githubusercontent.com/3431241/28637307-b4ba8798-7206-11e7-9c50-bb53afc4849b.jpg)

Also the success message is briefly displayed in place of the form before the user gets redirected. I tried changing the Redirect To option to ----- but it's a required field on the form. This doesn't make a ton of sense? It would be ideal if we didn't even have the grey alert and just utilized the text that gets added in place of the form. Because as soon as the user gets redirected, this text is gone and the form is back because it's a fresh page load.
![after-submit](https://user-images.githubusercontent.com/3431241/28637308-b4bcec86-7206-11e7-922d-eb0d177080a5.jpg)

So with the combination of these 2 issues, the user (being logged out) sees no confirmation that their form was sent.

**Comment by czpython** [comment]
Closed by https://github.com/aldryn/aldryn-forms/pull/141
