### ISSUE TITLE
One untranslatabe string in form advanced

### ISSUE THREAD

**Issue by PeterW-LWL** [aldryn/aldryn-forms#125]
In the image below i marked the untranslatable text.

![Untranslated text marked](https://user-images.githubusercontent.com/14937653/29079371-536770d0-7c5d-11e7-8719-083af829d2da.png)

I search in the source code to find the place this text gets rendered, but wasn't able to find it.

**Comment by czpython** [comment]
The `EmailNotification` proxy model is missing the `verbose_name` and `verbose_name_plural` attributes.
