### ISSUE TITLE
Missing migration aldryn_forms/migrations/0012_auto_*

### ISSUE THREAD

**Issue by alexandrenorman** [aldryn/aldryn-forms#154]
Missing migration 0012 for aldryn_forms in the repo and aldryn_forms 3.0.0

```
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0011_auto_20180110_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('none', 'None'), ('email_only', 'Email only'), ('default', 'Default')], default='default', max_length=15, verbose_name='Action backend'),
        ),
    ]
```

**Comment by czpython** [comment]
Closing as duplicate of https://github.com/aldryn/aldryn-forms/issues/147

**Comment by alexandrenorman** [comment]
Ok, you changed history for migration 0009.
So what do you plan for users that already installed version 2.3.0+ from pip ?
Wrong migration 0009 have been applied and won't be launched again except if told so by migrating back 0008 and apply again.

**Comment by czpython** [comment]
The reason why django requested a new migration was because of a change in choices.
No need to re-apply the 0009 migration, it doesn't affect the database in any way.

**Comment by alexandrenorman** [comment]
You're right. Sorry.
