### ISSUE TITLE
refactor FormData model

### ISSUE THREAD

**Issue by czpython** [aldryn/aldryn-forms#26]
We need a better way to store data in the model, to allow us to keep track of field positions in the form and labels, otherwise export becomes very tricky.

### Braindump

Considering the user can move fields around and also change their labels, there's really no 100% accurate way of properly exporting the data, for example:

User creates form with field A and B then let's say 5 people submit the form, after the 5th person, the admin comes and modifies the form to add a new field C, then 5 more people submit the form. So since the new field C was introduced after the first 5 submissions, then the export file will NOT have a value for column C for the first 5 submissions, but it will for the other 5.

Now, since field C is a new field then somehow I need to know it exists and put this new field in the export file header, so to do this I rely on the latest form submitted of the chosen type and then use the fields on that form to build the export file header, I use the latest in order to keep up with user changes. In other words, the user can add / remove as many fields as they want, the export file will only reflect the state of the latest submitted form.

Also, if a field gets moved or changes it's label then there's sadly no way to match that field with it's value on export for forms that were submitted before the field change, this is  because of a flaw on how the form data is stored.

**Comment by trawick** [comment]
Close this ticket?

**Comment by czpython** [comment]
Fixed by b50e03996aaea58e99f95d7d4758ab65591b5d63
