### ISSUE TITLE
max_value error in text field.

### ISSUE THREAD

**Issue by nick-ernie** [aldryn/aldryn-forms#64]
Hi guys.

I've found that when we trying to set max length in text field plugin, we have an error "object of type 'int' has no len()", because of validators=[MaxLengthValidator(255)] in max_value field of FieldPluginBase, so, i think it should be replaced to MaxValueValidator or custom validator to check integer length.

Thanks.

**Comment by nick-ernie** [comment]
Same for Multiple Select Field

**Comment by fmarco** [comment]
+1

**Comment by yakky** [comment]
Confirmed :+1:

**Comment by czpython** [comment]
Thanks! Will push a fix later today if no one beats me to it ;)
