### ISSUE TITLE
Notorious form data issue

### ISSUE THREAD

**Issue by czpython** [aldryn/aldryn-forms#65]
Currently, the way form data is stored is by combining all fields and values into a single string.
Each field/value combo is joined by a  ``:`` character and separated from the others via a newline.
This was an early not well thought out design decision because it means that any field that has a value with a ``:`` in it will cause Aldryn Forms to think that this value is it's own field.
This affects the importing and storing of form data as pointed out here https://github.com/aldryn/aldryn-forms/blob/master/aldryn_forms/models.py#L395.

I propose that instead of storing all field/values together, we either use a json field (with ordering) or an array field with the field/value pairs. This should be fairly simple to implement but my concern is backwards compatibility, this has to be backwards compatible which means we need a data migration that uses existing logic to separate each field/value pair from the stored string and then store them in the new json or array field, sadly there's no 100% reliable way we can actually tell if a field in the string is valid because of the issue mentioned above, to make it more reliable we could verify each found field with the form plugin fields but this would still not be 100% reliable because the idea behind form data was that the form plugin can be deleted without affecting anything in the stored data.

Thoughts?

**Comment by mkoistinen** [comment]
Sounds like you're proposing the right way forward to me.

**Comment by yakky** [comment]
I agree on the general idea.
We should use plain TextField with externally encoded json, though, to be compatible with every database instead of relying on specific field type (if I understand correctly the jsonfield / array field mentions)

**Comment by czpython** [comment]
@yakky yes is why I think we should use https://github.com/bradjasper/django-jsonfield which uses a textfield for representation and takes care of serialization and such

**Comment by yakky** [comment]
@czpython  "django-jsonfield is looking for maintainers" :(

**Comment by czpython** [comment]
So I've tried to find a way to cleanup the old form submissions to match proper fields in the form,
unfortunately because form submissions have no direct relationships to the form except for a name
and because of the big ``:`` problem, it's just impossible to accurately determine which entries are fields and which are not.

To properly fix this going forward, I've decided to create another model for form data that will have the new form structure as json (without using json field). The structure will include the field type, field label and field value.

The old structure will remain in the admin/db to be slowly deprecated and allow time to export this data.

Migrating the old data format to the new is not possible because things like field type are impossible to know from the old format.

**Comment by yakky** [comment]
@czpython looks perfectly reasonable

**Comment by fmarco** [comment]
+1

**Comment by trawick** [comment]
Close this ticket?

**Comment by czpython** [comment]
Yes, thanks!.
Fixed by b50e03996aaea58e99f95d7d4758ab65591b5d63
